### ISSUE TITLE
config_header.h problem

### ISSUE THREAD

**Issue by beastieboy** [pellepl/arcadehid#3]
The file config_header.h should be generated during make but it fails. Is it important?

**Comment by pellepl** [comment]
If memory serves, yes. It is however only a reformatting of config.mk, making all variables defines. What's the error and what os are you compiling on?

**Comment by beastieboy** [comment]
At the moment I try to compile it under MacOS. I don't think it's possible without radical config reformatting. The error I receive is like that:

```
bash-3.2$ CROSS_COMPILE=/Users/beastieboy/opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi- make all
... depend build/stm32f10x_it.d
In file included from ./src/system_config.h:11:0,
                 from gitsub/generic_embedded/src/system.h:11,
                 from src/stm32f10x_it.c:1:
./src/config_header.h:3:0: error: unterminated #ifndef
 #ifndef _CONFIG_HEADER_H
 
./src/config_header.h:2:0: error: unterminated #ifdef
 #ifdef INCLUDE_CONFIG_HEADER
```

This is a result of corrupt system_config.h which is not generated properly. Maybe you can just post here SDK/libraries versions you used to compile?

**Comment by beastieboy** [comment]
And maybe you can give a small hint how to prepare STM32 board for this project, should I flash a special HID bootloader first?

**Comment by beastieboy** [comment]
Compiles flawlessly under Ubuntu. Closing.
